stages:
  validate:
    cmd: python -m src.validate_env
    deps:
      - src/validate_env.py
      - .env

  download_data:
    cmd: python -m data.download_data
    deps:
      - data/download_data.py
      - .env
    outs:
      - data/raw/diabetes.csv

  ingest:
    cmd: python -m src.ingestion
    deps:
      - src/ingestion.py
      - data/raw/diabetes.csv
      - .env

  preprocess:
    cmd: python -m src.preprocessing
    deps:
      - src/preprocessing.py
      - .env
    outs:
      - data/processed/processed.parquet

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - data/processed/processed.parquet
      - .env
    outs:
      - model.pkl
